# Spendly Production Stack - Simple Version (No Nginx)
version: '3.8'

services:
  # Init container to create directories
  init-dirs:
    image: alpine:latest
    container_name: spendly-init-dirs
    volumes:
      - /opt/spendly/data:/data
    command: >
      sh -c '
        echo "ðŸ—ï¸ Creating required directories..." &&
        mkdir -p /data/postgres /data/uploads /data/logs &&
        chown -R 1000:1000 /data/uploads /data/logs 2>/dev/null || true &&
        echo "âœ… Directories created successfully"
      '
    restart: "no"

  # Database
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      - POSTGRES_DB=${DB_NAME:-spendly_prod}
      - POSTGRES_USER=${DB_USER:-spendly_user}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /opt/spendly/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-spendly_user} -d ${DB_NAME:-spendly_prod}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      init-dirs:
        condition: service_completed_successfully

  # Backend Service - Using completely different ports
  backend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:backend
      dockerfile: Dockerfile.prod
    container_name: spendly-backend
    ports:
      - "9000:8001"  # External:Internal - backend runs on 8001 internally
    environment:
      - ENVIRONMENT=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4000}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:9000}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:4000}
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-spendly_prod}
      - DB_USER=${DB_USER:-spendly_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgresql://${DB_USER:-spendly_user}:${DB_PASSWORD}@database:5432/${DB_NAME:-spendly_prod}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - CORS_CREDENTIALS=true
      - PORT=8001  # Tell backend to run on port 8001 instead of 8000
    volumes:
      - /opt/spendly/data/uploads:/app/uploads
      - /opt/spendly/data/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Service - Using port 4000
  frontend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:9000}/api/v1
        - REACT_APP_UPLOAD_URL=${BACKEND_URL:-http://localhost:9000}/uploads
    container_name: spendly-frontend
    environment:
      - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:9000}/api/v1
      - REACT_APP_UPLOAD_URL=${BACKEND_URL:-http://localhost:9000}/uploads
    ports:
      - "4000:80"  # External:Internal - using port 4000 for frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy
