# Working Portainer Stack - Builds from Git Repository
# This version uses build contexts that work in Portainer
version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.24-alpine
    container_name: spendly-nginx
    ports:
      - "8080:80"
    volumes:
      - /opt/spendly/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/spendly/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/spendly/data/uploads:/uploads:ro
      - /opt/spendly/data/nginx-logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"] 
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=/api/v1
        - REACT_APP_UPLOAD_URL=/uploads
    container_name: spendly-frontend
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Service
  backend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:backend
      dockerfile: Dockerfile.prod
    container_name: spendly-backend
    environment:
      - ENVIRONMENT=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FRONTEND_URL=https://spendly.ayoublefhim.com
      - BACKEND_URL=https://spendly.ayoublefhim.com
      - CORS_ORIGIN=https://spendly.ayoublefhim.com
      # Database Configuration
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=spendly_prod
      - DB_USER=spendly_user
      - DB_PASSWORD=88gv^rt8Lkv&&ffNrwy2iV
      - DB_URL=postgresql://spendly_user:88gv^rt8Lkv&&ffNrwy2iV@database:5432/spendly_prod
      # JWT Configuration
      - JWT_SECRET=f366ece0a833b680920ad9046e5d1ba1034ab7f3a0afe5c18ab7c844e539f341
      - JWT_EXPIRE=7d
      - JWT_ALGORITHM=HS256
      # Security
      - BCRYPT_ROUNDS=12
      - CORS_CREDENTIALS=true
    volumes:
      - /opt/spendly/data/uploads:/app/uploads
      - /opt/spendly/data/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database Service
  database:
    image: postgres:15-alpine
    container_name: spendly-database
    environment:
      - POSTGRES_DB=spendly_prod
      - POSTGRES_USER=spendly_user
      - POSTGRES_PASSWORD=88gv^rt8Lkv&&ffNrwy2iV
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /opt/spendly/data/postgres:/var/lib/postgresql/data
      - /opt/spendly/data/backups:/backups
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spendly_user -d spendly_prod"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Database Backup Service
  backup:
    image: postgres:15-alpine
    container_name: spendly-backup
    environment:
      - PGHOST=database
      - PGDATABASE=spendly_prod
      - PGUSER=spendly_user
      - PGPASSWORD=88gv^rt8Lkv&&ffNrwy2iV
    volumes:
      - /opt/spendly/data/backups:/backups
      - /opt/spendly/data/uploads:/uploads:ro
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - spendly-network
    command: |
      sh -c '
        echo "0 2 * * * pg_dump > /backups/spendly_backup_$$(date +%Y%m%d_%H%M%S).sql && find /backups -name \"*.sql\" -mtime +30 -delete" | crontab -
        crond -f
      '

networks:
  spendly-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
