# Spendly Production Deployment with Nginx Proxy Manager
version: '3.8'

services:
  # Nginx Proxy Manager - Web UI for managing SSL certificates and proxy hosts
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: spendly-nginx-proxy-manager
    restart: unless-stopped
    ports:
      # Public HTTP/HTTPS ports
      - '80:80'     # HTTP traffic
      - '443:443'   # HTTPS traffic  
      - '81:81'     # Admin Web UI (change this port for security)
    environment:
      # Optional: Set custom database settings
      # DB_MYSQL_HOST: "nginx-proxy-manager-db"
      # DB_MYSQL_PORT: 3306
      # DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
      # DB_MYSQL_NAME: "npm"
      
      # Use SQLite by default (simpler setup)
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      # Optional: Custom nginx configurations
      - ./config/nginx-proxy-manager:/data/nginx/custom:ro
    networks:
      - spendly-network
      - npm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81/api"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MySQL database for Nginx Proxy Manager (uncomment if you prefer MySQL over SQLite)
  # nginx-proxy-manager-db:
  #   image: 'mysql:8.0'
  #   container_name: spendly-nginx-proxy-manager-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${NPM_DB_ROOT_PASSWORD}"
  #     MYSQL_DATABASE: "npm"
  #     MYSQL_USER: "npm"
  #     MYSQL_PASSWORD: "${NPM_DB_PASSWORD}"
  #   volumes:
  #     - npm_mysql_data:/var/lib/mysql
  #   networks:
  #     - npm-network

  # Database
  database:
    image: postgres:15-alpine
    container_name: spendly-database
    environment:
      - POSTGRES_DB=${DB_NAME:-spendly_prod}
      - POSTGRES_USER=${DB_USER:-spendly_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-spendly_user} -d ${DB_NAME:-spendly_prod}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - spendly-network
    # Remove external port exposure since we're using proxy manager
    # ports:
    #   - "5432:5432"

  # Backend Service
  backend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:backend
      dockerfile: Dockerfile.prod
    container_name: spendly-backend
    # Remove external port exposure - only accessible via proxy manager
    expose:
      - "8001"
    environment:
      - ENVIRONMENT=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PORT=8001
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-spendly_prod}
      - DB_USER=${DB_USER:-spendly_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgresql://${DB_USER:-spendly_user}:${DB_PASSWORD}@database:5432/${DB_NAME:-spendly_prod}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - CORS_ORIGIN=${CORS_ORIGIN:-https://spendly.ayoublefhim.com}
      - CORS_CREDENTIALS=true
      - FRONTEND_URL=${FRONTEND_URL:-https://spendly.ayoublefhim.com}
      - BACKEND_URL=${BACKEND_URL:-https://spendly.ayoublefhim.com}
      - UPLOAD_PATH=/app/uploads
      - UPLOAD_URL=${BACKEND_URL:-https://spendly.ayoublefhim.com}/uploads
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - spendly-network

  # Frontend Service - Updated for proxy manager
  frontend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:frontend
      dockerfile: Dockerfile.prod
      args:
        - CI=false
        - REACT_APP_API_URL=${BACKEND_URL:-https://spendly.ayoublefhim.com}/api/v1
        - REACT_APP_UPLOAD_URL=${BACKEND_URL:-https://spendly.ayoublefhim.com}/uploads
    container_name: spendly-frontend
    # Remove external port exposure - only accessible via proxy manager
    expose:
      - "80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend
    networks:
      - spendly-network

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower
    container_name: spendly-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400  # Check every 24 hours
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
    networks:
      - spendly-network

networks:
  spendly-network:
    driver: bridge
  npm-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  # npm_mysql_data:  # Uncomment if using MySQL for NPM
  #   driver: local
