# Spendly Production Stack for Portainer
# Clean, organized, and uses environment variables properly
version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.24-alpine
    container_name: spendly-nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - spendly-network
    volumes:
      - /opt/spendly/data/uploads:/uploads:ro
      - /opt/spendly/data/nginx-logs:/var/log/nginx
    command: |
      sh -c '
        # Install curl for health checks
        apk add --no-cache curl
        
        # Create simple nginx configuration
        cat > /etc/nginx/conf.d/default.conf << "EOF"
        server {
            listen 80;
            server_name _;
            
            location /health {
                return 200 "nginx healthy";
                add_header Content-Type text/plain;
            }
            
            location / {
                proxy_pass http://frontend:80;
                proxy_set_header Host \$$host;
                proxy_set_header X-Real-IP \$$remote_addr;
                proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$$scheme;
            }
            
            location /api/ {
                proxy_pass http://backend:8000;
                proxy_set_header Host \$$host;
                proxy_set_header X-Real-IP \$$remote_addr;
                proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$$scheme;
            }
            
            location /uploads/ {
                proxy_pass http://backend:8000;
                proxy_set_header Host \$$host;
                client_max_body_size 50m;
            }
        }
        EOF
        
        # Start nginx
        nginx -g "daemon off;"
      '

  # Frontend Service
  frontend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=/api/v1
        - REACT_APP_UPLOAD_URL=/uploads
    container_name: spendly-frontend
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Service
  backend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:backend
      dockerfile: Dockerfile.prod
    container_name: spendly-backend
    env_file:
      - env.production

    volumes:
      - /opt/spendly/data/uploads:/app/uploads
      - /opt/spendly/data/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database Service
  database:
    image: postgres:15-alpine
    container_name: spendly-database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /opt/spendly/data/postgres:/var/lib/postgresql/data
      - /opt/spendly/data/backups:/backups
    restart: unless-stopped
    networks:
      - spendly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spendly_user -d spendly_prod"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Database Backup Service
  backup:
    image: postgres:15-alpine
    container_name: spendly-backup
    environment:
      - PGHOST=database
      - PGDATABASE=${DB_NAME}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - /opt/spendly/data/backups:/backups
      - /opt/spendly/data/uploads:/uploads:ro
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - spendly-network
    command: |
      sh -c '
        echo "0 2 * * * pg_dump > /backups/spendly_backup_$$(date +%Y%m%d_%H%M%S).sql && find /backups -name \"*.sql\" -mtime +30 -delete" | crontab -
        crond -f
      '

networks:
  spendly-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  nginx_config:
