# Spendly Production Deployment
version: '3.8'

services:
  # Database
  database:
    image: postgres:15-alpine
    container_name: spendly-database
    environment:
      - POSTGRES_DB=${DB_NAME:-spendly_prod}
      - POSTGRES_USER=${DB_USER:-spendly_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-spendly_user} -d ${DB_NAME:-spendly_prod}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - spendly-network

  # Backend Service
  backend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:backend
      dockerfile: Dockerfile.prod
    container_name: spendly-backend
    ports:
      - "9000:8001"
    environment:
      - ENVIRONMENT=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PORT=8001
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-spendly_prod}
      - DB_USER=${DB_USER:-spendly_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=postgresql://${DB_USER:-spendly_user}:${DB_PASSWORD}@database:5432/${DB_NAME:-spendly_prod}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:4000}
      - CORS_CREDENTIALS=true
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4000}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:9000}
      - UPLOAD_PATH=/app/uploads
      - UPLOAD_URL=${BACKEND_URL:-http://localhost:9000}/uploads
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - spendly-network

  # Frontend Service
  frontend:
    build:
      context: https://github.com/Ayoubl96/Spendly.git#main:frontend
      dockerfile: Dockerfile.prod
      args:
        - CI=false
        - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:9000}/api/v1
        - REACT_APP_UPLOAD_URL=${BACKEND_URL:-http://localhost:9000}/uploads
    container_name: spendly-frontend
    ports:
      - "4000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend
    networks:
      - spendly-network

networks:
  spendly-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local
