"""fix_model_database_sync

Revision ID: 2303231c16f8
Revises: f414d6f9c9e
Create Date: 2025-08-31 00:41:11.907343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2303231c16f8'
down_revision: Union[str, None] = 'f414d6f9c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_connections', 'refresh_token')
    op.drop_column('bank_connections', 'access_token')
    op.drop_constraint('fk_budgets_budget_group_id', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'budget_groups', ['budget_group_id'], ['id'])
    # Add updated_at column to exchange_rates with default value
    op.add_column('exchange_rates', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.create_foreign_key(None, 'exchange_rates', 'currencies', ['to_currency'], ['code'])
    op.create_foreign_key(None, 'exchange_rates', 'currencies', ['from_currency'], ['code'])
    
    # Add updated_at column to expense_attachments with default value
    op.add_column('expense_attachments', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    
    op.drop_constraint('fk_expenses_payment_method_id', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'user_payment_methods', ['payment_method_id'], ['id'])
    
    # Add timestamp columns to imported_transactions with default values
    op.add_column('imported_transactions', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('imported_transactions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.alter_column('shared_expenses', 'share_percentage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shared_expenses', 'share_amount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Add timestamp columns to transaction_import_logs with default values
    op.add_column('transaction_import_logs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('transaction_import_logs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_import_logs', 'updated_at')
    op.drop_column('transaction_import_logs', 'created_at')
    op.alter_column('shared_expenses', 'share_amount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shared_expenses', 'share_percentage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('imported_transactions', 'updated_at')
    op.drop_column('imported_transactions', 'created_at')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('fk_expenses_payment_method_id', 'expenses', 'user_payment_methods', ['payment_method_id'], ['id'], ondelete='SET NULL')
    op.drop_column('expense_attachments', 'updated_at')
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.drop_column('exchange_rates', 'updated_at')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('fk_budgets_budget_group_id', 'budgets', 'budget_groups', ['budget_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('bank_connections', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bank_connections', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
