"""change something on table bank connection

Revision ID: 2609c4283fca
Revises: 8d9aa2eadcae
Create Date: 2025-09-14 16:52:33.499071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2609c4283fca'
down_revision: Union[str, None] = '8d9aa2eadcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_tasksetmeta')
    op.drop_index(op.f('ix_kombu_message_timestamp'), table_name='kombu_message')
    op.drop_index(op.f('ix_kombu_message_timestamp_id'), table_name='kombu_message')
    op.drop_index(op.f('ix_kombu_message_visible'), table_name='kombu_message')
    op.drop_table('kombu_message')
    op.drop_table('kombu_queue')
    op.drop_table('celery_taskmeta')
    op.alter_column('transaction_import_logs', 'transaction_skipped',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_import_logs', 'expenses_created',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_import_logs', 'expenses_created',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_import_logs', 'transaction_skipped',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_taskmeta_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('celery_taskmeta_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('kombu_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kombu_queue_pkey'),
    sa.UniqueConstraint('name', name='kombu_queue_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('kombu_message',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['kombu_queue.id'], name=op.f('FK_kombu_message_queue')),
    sa.PrimaryKeyConstraint('id', name=op.f('kombu_message_pkey'))
    )
    op.create_index(op.f('ix_kombu_message_visible'), 'kombu_message', ['visible'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp_id'), 'kombu_message', ['timestamp', 'id'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp'), 'kombu_message', ['timestamp'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_tasksetmeta_pkey')),
    sa.UniqueConstraint('taskset_id', name=op.f('celery_tasksetmeta_taskset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
