"""telegram table and update bbank connection table

Revision ID: 78e6f994c3bc
Revises: f4df71e33fb6
Create Date: 2025-09-14 02:59:26.747227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e6f994c3bc'
down_revision: Union[str, None] = 'f4df71e33fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_connections', sa.Column('telegram_notification', sa.Boolean(), nullable=True))
    op.add_column('bank_connections', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_budgets_budget_group_id'), 'budgets', type_='foreignkey')
    op.drop_constraint(op.f('fk_expenses_payment_method_id'), 'expenses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_expenses_payment_method_id'), 'expenses', 'user_payment_methods', ['payment_method_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_budgets_budget_group_id'), 'budgets', 'budget_groups', ['budget_group_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bank_connections', 'telegram_chat_id')
    op.drop_column('bank_connections', 'telegram_notification')
    # ### end Alembic commands ###
