"""telegram table

Revision ID: 8d9aa2eadcae
Revises: 78e6f994c3bc
Create Date: 2025-09-14 03:03:39.921285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9aa2eadcae'
down_revision: Union[str, None] = '78e6f994c3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_configuration_id'), 'telegram_configuration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_configuration_id'), table_name='telegram_configuration')
    op.drop_table('telegram_configuration')
    # ### end Alembic commands ###
