"""update bankconnection table with account_uid

Revision ID: a59ffd70f1aa
Revises: f2d253da85b8
Create Date: 2025-08-31 10:31:11.763714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59ffd70f1aa'
down_revision: Union[str, None] = 'f2d253da85b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_connections', sa.Column('account_uid', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_bank_connections_account_uid'), 'bank_connections', ['account_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_connections_account_uid'), table_name='bank_connections')
    op.drop_column('bank_connections', 'account_uid')
    # ### end Alembic commands ###
