"""change on bank connection table column session_id to not unique

Revision ID: f2d253da85b8
Revises: 2303231c16f8
Create Date: 2025-08-31 01:15:57.567329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d253da85b8'
down_revision: Union[str, None] = '2303231c16f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_connections_session_id'), table_name='bank_connections')
    op.create_index(op.f('ix_bank_connections_session_id'), 'bank_connections', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_connections_session_id'), table_name='bank_connections')
    op.create_index(op.f('ix_bank_connections_session_id'), 'bank_connections', ['session_id'], unique=True)
    # ### end Alembic commands ###
